export const IPC = {
  APP: {
    GET_INFO: "app:getInfo",
  },
  CLIENT: {
    DISCONNECT: "client:disconnect",
    GET_STATUS: "client:getStatus",
    ON_STATUS_CHANGE: "client:onStatusChange",
  },
  CHAT: {
    SEND_MESSAGE: "chat:sendMessage",
    SEND_IMAGE: "chat:sendImage",
    SEND_AUDIO: "chat:sendAudio",
    DOWNLOAD_AUDIO: "chat:downloadAudio",
    PICK_IMAGE: "chat:pickImage",
    DOWNLOAD_IMAGE: "chat:downloadImage",
    SEND_FILE: "chat:sendFile",
    PICK_FILE: "chat:pickFile",
    DOWNLOAD_FILE: "chat:downloadFile",
    OPEN_FILE: "chat:openFile",
    GET_MESSAGES: "chat:getMessages",
    START_SESSION: "chat:startSession",
    MARK_READ: "chat:markRead",
    SET_ACTIVE_SESSION: "chat:setActiveSession",
    ON_MESSAGE: "chat:onMessage",
    ON_NAVIGATE_TO_SESSION: "chat:onNavigateToSession",
    ON_MESSAGE_BURNED: "chat:onMessageBurned",
  },
  CONTACT: {
    ADD: "contact:add",
    LIST: "contact:list",
    GET: "contact:get",
    DELETE: "contact:delete",
    UPDATE: "contact:update",
    PICK_AVATAR: "contact:pickAvatar",
    SET_AVATAR: "contact:setAvatar",
    ON_UPDATE: "contact:onUpdate",
    SET_BURN_OPTIONS: "contact:setBurnOptions",
  },
  WALLET: {
    CREATE_AND_CONNECT: "wallet:createAndConnect",
    IMPORT_AND_CONNECT: "wallet:importAndConnect",
    RESTORE_AND_CONNECT: "wallet:restoreAndConnect",
    AUTO_CONNECT: "wallet:autoConnect",
    HAS_SAVED: "wallet:hasSaved",
    LOGOUT: "wallet:logout",
    GET_BALANCE: "wallet:getBalance",
    TRANSFER: "wallet:transfer",
    ADDRESS_FROM_CLIENT: "wallet:addressFromClient",
    EXPORT_KEYSTORE: "wallet:exportKeystore",
    IMPORT_KEYSTORE_FILE: "wallet:importKeystoreFile",
  },
  CLIENT_EXTRA: {
    ECHO_TEST: "client:echoTest",
  },
  SESSION: {
    LIST: "session:list",
    GET: "session:get",
    DELETE: "session:delete",
    SET_MUTED: "session:setMuted",
    ON_UPDATE: "session:onUpdate",
    ON_DELETE: "session:onDelete",
  },
  SETTINGS: {
    GET: "settings:get",
    SET: "settings:set",
  },
  TOPIC: {
    CREATE: "topic:create",
    JOIN: "topic:join",
    LEAVE: "topic:leave",
    LIST: "topic:list",
    GET: "topic:get",
    GET_SUBSCRIBERS: "topic:getSubscribers",
    REFRESH_SUBSCRIBERS: "topic:refreshSubscribers",
    SEND_MESSAGE: "topic:sendMessage",
    SEND_IMAGE: "topic:sendImage",
    SEND_AUDIO: "topic:sendAudio",
    SEND_FILE: "topic:sendFile",
    ON_UPDATE: "topic:onUpdate",
    ON_DELETE: "topic:onDelete",
  },
  PROFILE: {
    GET: "profile:get",
    SET_NICKNAME: "profile:setNickname",
    PICK_AVATAR: "profile:pickAvatar",
    SET_AVATAR: "profile:setAvatar",
    ON_UPDATE: "profile:onUpdate",
  },
  DATABASE: {
    EXPORT: "database:export",
    RESTORE: "database:restore",
  },
  PRIVATE_GROUP: {
    CREATE: "privateGroup:create",
    LIST: "privateGroup:list",
    GET: "privateGroup:get",
    INVITE: "privateGroup:invite",
    ACCEPT: "privateGroup:accept",
    QUIT: "privateGroup:quit",
    KICK: "privateGroup:kick",
    GET_MEMBERS: "privateGroup:getMembers",
    REFRESH_MEMBERS: "privateGroup:refreshMembers",
    SEND_MESSAGE: "privateGroup:sendMessage",
    SEND_IMAGE: "privateGroup:sendImage",
    SEND_AUDIO: "privateGroup:sendAudio",
    SEND_FILE: "privateGroup:sendFile",
    ON_UPDATE: "privateGroup:onUpdate",
    ON_DELETE: "privateGroup:onDelete",
  },
  DISCOVERY: {
    LIST: "discovery:list",
    GET_CATEGORIES: "discovery:getCategories",
    REFRESH: "discovery:refresh",
    CREATE_GROUP: "discovery:createGroup",
    PICK_AVATAR: "discovery:pickAvatar",
    ON_UPDATE: "discovery:onUpdate",
  },
  BOT: {
    CREATE: "bot:create",
    GET: "bot:get",
    DELETE: "bot:delete",
  },
  VOICE: {
    START_CALL: "voice:startCall",
    ACCEPT_CALL: "voice:acceptCall",
    DECLINE_CALL: "voice:declineCall",
    END_CALL: "voice:endCall",
    SEND_AUDIO: "voice:sendAudio",
    ON_CALL_STATE: "voice:onCallState",
    ON_AUDIO_DATA: "voice:onAudioData",
    ON_INCOMING_CALL: "voice:onIncomingCall",
  },
} as const;
