export const IPC = {
  APP: {
    GET_INFO: "app:getInfo",
  },
  CLIENT: {
    CONNECT: "client:connect",
    DISCONNECT: "client:disconnect",
    GET_STATUS: "client:getStatus",
    ON_STATUS_CHANGE: "client:onStatusChange",
  },
  CHAT: {
    SEND_MESSAGE: "chat:sendMessage",
    SEND_IMAGE: "chat:sendImage",
    SEND_AUDIO: "chat:sendAudio",
    DOWNLOAD_AUDIO: "chat:downloadAudio",
    PICK_IMAGE: "chat:pickImage",
    DOWNLOAD_IMAGE: "chat:downloadImage",
    SEND_FILE: "chat:sendFile",
    PICK_FILE: "chat:pickFile",
    DOWNLOAD_FILE: "chat:downloadFile",
    OPEN_FILE: "chat:openFile",
    GET_MESSAGES: "chat:getMessages",
    START_SESSION: "chat:startSession",
    MARK_READ: "chat:markRead",
    ON_MESSAGE: "chat:onMessage",
  },
  CONTACT: {
    ADD: "contact:add",
    LIST: "contact:list",
    GET: "contact:get",
    DELETE: "contact:delete",
    UPDATE: "contact:update",
    PICK_AVATAR: "contact:pickAvatar",
    SET_AVATAR: "contact:setAvatar",
    ON_UPDATE: "contact:onUpdate",
  },
  WALLET: {
    CREATE: "wallet:create",
    IMPORT: "wallet:import",
    GET_BALANCE: "wallet:getBalance",
    EXPORT: "wallet:export",
    SAVE_SEED: "wallet:saveSeed",
    LOAD_SEED: "wallet:loadSeed",
    CLEAR_SEED: "wallet:clearSeed",
    TRANSFER: "wallet:transfer",
    ADDRESS_FROM_CLIENT: "wallet:addressFromClient",
  },
  CLIENT_EXTRA: {
    ECHO_TEST: "client:echoTest",
  },
  SESSION: {
    LIST: "session:list",
    GET: "session:get",
    DELETE: "session:delete",
    ON_UPDATE: "session:onUpdate",
    ON_DELETE: "session:onDelete",
  },
  SETTINGS: {
    GET: "settings:get",
    SET: "settings:set",
  },
  TOPIC: {
    CREATE: "topic:create",
    JOIN: "topic:join",
    LEAVE: "topic:leave",
    LIST: "topic:list",
    GET: "topic:get",
    GET_SUBSCRIBERS: "topic:getSubscribers",
    REFRESH_SUBSCRIBERS: "topic:refreshSubscribers",
    SEND_MESSAGE: "topic:sendMessage",
    SEND_IMAGE: "topic:sendImage",
    SEND_AUDIO: "topic:sendAudio",
    SEND_FILE: "topic:sendFile",
    ON_UPDATE: "topic:onUpdate",
    ON_DELETE: "topic:onDelete",
  },
  PROFILE: {
    GET: "profile:get",
    SET_NICKNAME: "profile:setNickname",
    PICK_AVATAR: "profile:pickAvatar",
    SET_AVATAR: "profile:setAvatar",
    ON_UPDATE: "profile:onUpdate",
  },
} as const;
